package hu.durasoft.phonebook;

import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import javafx.collections.ObservableList;

import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;

public class PdfGeneration {

    public void pdfGeneration(String fileName, ObservableList<Person> data) {
        Document document = new Document();
        try {
            PdfWriter.getInstance(document, new FileOutputStream(fileName + ".pdf"));
            document.open();
            Image image = Image.getInstance(getClass().getResource("logo.jpg"));
            image.scaleToFit(448, 252);
            image.setAbsolutePosition(70f, 570f);
            document.add(image);
            document.add(new Paragraph("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n"));

            float[] columnWidths = {1, 4, 4, 6};
            PdfPTable table = new PdfPTable(columnWidths);
            table.setWidthPercentage(100);
            PdfPCell cellTitle = new PdfPCell(new Phrase("Contact List"));
            cellTitle.setBackgroundColor(GrayColor.GRAYWHITE);
            cellTitle.setHorizontalAlignment(Element.ALIGN_CENTER);
            cellTitle.setColspan(4);
            table.addCell(cellTitle);
            table.getDefaultCell().setBackgroundColor(new GrayColor(0.75f));
            table.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);
            table.addCell("#");
            table.addCell("Last name");
            table.addCell("First name");
            table.addCell("E-mail address");
            table.setHeaderRows(1);
            table.getDefaultCell().setBackgroundColor(GrayColor.GRAYWHITE);
            table.getDefaultCell().setHorizontalAlignment(Element.ALIGN_CENTER);
            for (int i = 0; i < data.size(); i++) {
                table.addCell("" + (i + 1));
                table.addCell(data.get(i).getLastName());
                table.addCell(data.get(i).getFirstName());
                table.addCell(data.get(i).getEmail());
            }
            document.add(table);

            Chunk signature = new Chunk("\n\nGenerated by PhoneBook app.");
            Paragraph paragraph = new Paragraph(signature);
            document.add(paragraph);
        } catch (Exception e) {
            String message = "Something went wrong";
            Logger.getLogger(ViewController.class.getName()).log(Level.SEVERE, message, e);
        }
        document.close();
    }

}
